// apps/sandbox-angular/src/app/app.ts
import { ChangeDetectorRef, Component } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { InitProgressReport, MLCEngine } from '@mlc-ai/web-llm';
import { WebLLMService } from '@web-llm-wrappers/angular';

import { HlmButtonImports } from '@spartan-ng/helm/button';
import { HlmInputImports } from '@spartan-ng/helm/input';
import { BrnSelectImports } from '@spartan-ng/brain/select';
import { HlmSelectImports } from '@spartan-ng/helm/select';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { provideIcons } from '@ng-icons/core';
import { lucideChevronDown, lucideChevronUp } from '@ng-icons/lucide';

interface ChatMessage {
  content: string;
  role: 'user' | 'assistant' | 'system';
}

@Component({
  selector: 'app-root',
  imports: [
    HlmButtonImports,
    HlmInputImports,
    BrnSelectImports,
    HlmSelectImports,
    CommonModule,
    FormsModule,
  ],
  templateUrl: './app.html',
  styleUrl: './app.css',
  providers: [provideIcons({ lucideChevronUp, lucideChevronDown })],
})
export class App {
  messageStyles = {
    user: 'bg-blue-500 text-white self-end',
    assistant: 'bg-gray-200 text-black self-start',
    system: 'bg-green-500 text-white self-center',
  };

  protected availableModels: ReturnType<typeof WebLLMService.prototype.getAvailableModels> = [];
  protected selectedModel: string | string[] = '';
  protected modelLoaded = false;

  protected newMessage = '';
  protected chatHistory: ChatMessage[] = [
    {
      content: 'You are a helpful AI agent helping users.',
      role: 'system',
    },
  ];

  engine: MLCEngine | null = null;
  progressReport: InitProgressReport | null = null;

  constructor(
    private webLLMService: WebLLMService,
    private cd: ChangeDetectorRef,
  ) {
    this.availableModels = this.webLLMService.getAvailableModels();

    this.webLLMService.engine.pipe(takeUntilDestroyed()).subscribe((engine) => {
      this.engine = engine;
      this.cd.detectChanges();
    });

    this.webLLMService.progressReport.pipe(takeUntilDestroyed()).subscribe((progressReport) => {
      this.progressReport = progressReport;
      this.cd.detectChanges();
    });

    this.webLLMService.init(this.selectedModel).then(() => {
      console.log('WebLLM initialized');
    });
  }

  async downloadModel() {
    if (this.selectedModel) {
      await this.webLLMService.loadModel(this.selectedModel);
      this.modelLoaded = true;
    }
  }

  sendMessage(e: Event) {
    e.preventDefault();
    if (this.newMessage.trim() === '' || !this.engine || !this.modelLoaded) {
      return;
    }

    const newHistory = [...this.chatHistory, { content: this.newMessage, role: 'user' } as const];
    this.chatHistory = newHistory;
    this.newMessage = '';

    this.engine?.chat.completions
      .create({
        stream: true,
        messages: newHistory,
        temperature: 0,
      })
      .then(async (stream) => {
        let assistantMessage = '';
        for await (const chunk of stream) {
          assistantMessage += chunk.choices[0].delta.content || '';

          this.chatHistory = [
            ...newHistory,
            { content: assistantMessage, role: 'assistant' } as const,
          ];

          this.cd.detectChanges();
        }
      });
  }
}

// apps/sandbox-vue3/src/App.vue
<script setup lang="ts">
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Spinner } from "@/components/ui/spinner";

import { useWebLLM } from "@web-llm-wrappers/vue3";
import { ref } from "vue";

interface ChatMessage {
  content: string;
  role: "user" | "assistant" | "system";
}

const messageStyles = {
  user: "bg-blue-500 text-white self-end",
  assistant: "bg-gray-200 text-black self-start",
  system: "bg-green-500 text-white self-center",
};

const { engine, progressReport, getAvailableModels, loadModel } = useWebLLM({
  debug: true,
});

const availableModels = getAvailableModels();

const modelId = ref<string>();
const modelLoaded = ref(false);
const newMessage = ref("");
const chatHistory = ref<ChatMessage[]>([
  {
    content: "You are a helpful AI agent helping users.",
    role: "system",
  },
]);

function downloadModel() {
  if (modelId.value) {
    modelLoaded.value = false;
    loadModel(modelId.value)?.then(() => {
      modelLoaded.value = true;
    });
  }
}

function sendMessage() {
  if (newMessage.value.trim() === "" || !engine || !modelLoaded.value) {
    return;
  }

  const newHistory = [
    ...chatHistory.value,
    { content: newMessage.value, role: "user" } as const,
  ];
  chatHistory.value = newHistory;
  newMessage.value = "";

  engine.chat.completions
    .create({
      stream: true,
      messages: newHistory,
      temperature: 0,
    })
    .then(async (stream) => {
      let assistantMessage = "";
      for await (const chunk of stream) {
        assistantMessage += chunk.choices[0].delta.content || "";

        chatHistory.value = [
          ...newHistory,
          { content: assistantMessage, role: "assistant" } as const,
        ];
      }
    });
}
</script>

<template>
  <p>Step 1: Initialize WebLLM and Download Model</p>
  <div class="download-container flex flex-row gap-4">
    <Select v-model="modelId">
      <SelectTrigger>
        <SelectValue>
          {{ modelId || "Select Model" }}
        </SelectValue>
      </SelectTrigger>
      <SelectContent>
        <SelectItem
          v-for="model in availableModels"
          :key="model.model_id"
          :value="model.model_id"
        >
          {{ model.model_id }}
        </SelectItem>
      </SelectContent>
    </Select>
    <Button id="download" @click="downloadModel">Download</Button>
  </div>
  <p id="download-status" v-if="progressReport">
    {{ progressReport.text }}
  </p>

  <p>Step 2: Chat</p>
  <div class="chat-container">
    <div id="chat-box" className="chat-box flex flex-col">
      <div
        v-for="(msg, index) in chatHistory"
        :key="{ index }"
        :class="`chat-message ${messageStyles[msg.role]}`"
      >
        <span>{{ msg.content }}</span>
      </div>
    </div>
    <div id="chat-stats" class="chat-stats hidden"></div>
    <form class="chat-input-container" @submit.prevent="sendMessage">
      <Input
        type="text"
        id="user-input"
        placeholder="Type a message..."
        v-model="newMessage"
      />
      <Button id="send" :disabled="!modelLoaded">Send</Button>
    </form>
  </div>
</template>

<style scoped></style>
